default_language_version:
  python: python3.10

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: uv run pyupgrade --py38-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: uv run isort --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black --config pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        types: [python]
        language: system
        pass_filenames: false
