[build-system]
requires = ["hatchling>=1.4.0"]
build-backend = "hatchling.build"

[project]
name = "ryoma_ai"
version = "0.0.1"
description = "AI Powered Data Platform"
readme = "README.md"
repository = "https://github.com/project-ryoma/ryoma"
homepage = "https://www.ryoma-ai.com"
requires-python = ">=3.9"

keywords = ["Artificial Intelligence", "Data Analysis", "Code Generation"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

dependencies = [
  "mock>=5.1.0",
  "openai>=1.33.0",
  "pydantic>=2.7.1",
  "jupyter-ai-magics>=2.19.0",
  "pandas>=2.2.2",
  "langchain-openai>=0.1.7",
  "langchain>=0.2.9, <0.3.0",
  "langgraph>=0.1.9",
  "ipython>=8.14.0",
  "pyarrow>=16.1.0",
  "typer>=0.12.3",
  "types-setuptools>=70.0.0.20240524",
]
