[build-system]
requires = ["hatchling>=1.4.0"]
build-backend = "hatchling.build"

[project]
name = "ryoma_ai"
version = "0.0.2"
description = "AI Powered Data Platform"
readme = "README.md"
repository = "https://github.com/project-ryoma/ryoma"
homepage = "https://www.ryoma-ai.com"
requires-python = ">=3.9"

keywords = ["Artificial Intelligence", "Data Analysis", "Code Generation"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

dependencies = [
  "mock>=5.1.0",
  "openai>=1.33.0",
  "pydantic>=2.7.1",
  "jupyter-ai-magics>=2.19.0",
  "pandas>=2.2.2",
  "langchain-openai>=0.1.7",
  "langchain>=0.2.9, <0.3.0",
  "langgraph>=0.2.0",
  "ipython>=8.14.0",
  "pyarrow>=16.1.0",
  "typer>=0.12.3",
  "types-setuptools>=70.0.0.20240524",
  "datasketch>=1.6.5",
  "httpx==0.27.2",
  "click>=8.0.0",
  "rich>=13.0.0"
]

[project.scripts]
ryoma-sql = "ryoma_ai.cli.main:main"

[project.optional-dependencies]
snowflake = [
    "ibis-framework[snowflake]>=9.0.0",
    "amundsen-databuilder[snowflake]>=7.5.0",
    "feast[snowflake]>=0.39.1"
]
sqlite = [
    "ibis-framework[sqlite]>=9.0.0",
    "feast[sqlite]>=0.39.1",
]
postgres = [
    "psycopg2>=2.9.2",
    "ibis-framework[postgres]>=9.0.0",
    "amundsen-databuilder[postgres]>=7.5.0",
    "feast[postgres]>=0.39.1"
]
mysql = [
    "ibis-framework[mysql]>=9.0.0",
    "amundsen-databuilder[mysql]>=7.5.0",
    "feast[mysql]>=0.39.1"
]
bigquery = [
    "ibis-framework[bigquery]>=9.0.0",
    "amundsen-databuilder[bigquery]>=7.5.0",
    "feast[bigquery]>=0.39.1"
]
pyspark = [
    "ibis-framework[pyspark]>=9.0.0",
    "pyspark>=3.2.0",
    "findspark>=1.4.2",
    "feast[pyspark]>=0.39.1"
]
