"""empty message

Revision ID: 2f7b84eb351a
Revises: 89210f5009d4
Create Date: 2024-06-28 17:48:59.241793

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f7b84eb351a"
down_revision: Union[str, None] = "89210f5009d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vectorstore",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("online_store_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("offline_store_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("online_store_configs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("offline_store_configs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_configs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vectorstore")
    # ### end Alembic commands ###
