"""empty message

Revision ID: 34dd3ed73def
Revises: 32c47e486eed
Create Date: 2025-08-13 23:10:17.202491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '34dd3ed73def'
down_revision: Union[str, None] = '32c47e486eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vectorstore')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vectorstore',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_name', sa.VARCHAR(), nullable=False),
    sa.Column('online_store', sa.VARCHAR(), nullable=False),
    sa.Column('online_store_configs', sa.VARCHAR(), nullable=True),
    sa.Column('offline_store', sa.VARCHAR(), nullable=False),
    sa.Column('offline_store_configs', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('documentproject')
    # ### end Alembic commands ###
