"""empty message

Revision ID: 3cd25d13d812
Revises: e4f38c467755
Create Date: 2024-06-23 16:22:02.712821

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cd25d13d812"
down_revision: Union[str, None] = "e4f38c467755"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.alter_column("quesetion", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("answer", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.alter_column("answer", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("quesetion", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
