"""empty message

Revision ID: 4175a2d27d6c
Revises: 
Create Date: 2024-06-20 00:36:30.843351

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4175a2d27d6c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalogtable",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datasource_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("catalog_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("schema", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("table", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datasource",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("datasource_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("connection_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("datasource")
    op.drop_table("catalogtable")
    # ### end Alembic commands ###
