"""empty message

Revision ID: 89210f5009d4
Revises: c98b9ff107ce
Create Date: 2024-06-23 20:33:37.198236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '89210f5009d4'
down_revision: Union[str, None] = 'c98b9ff107ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('quesetion')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quesetion', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('question')

    # ### end Alembic commands ###
