"""empty message

Revision ID: 9dc23e9c4dd5
Revises: 0da41a57cfc3
Create Date: 2024-08-18 17:15:35.830855

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dc23e9c4dd5"
down_revision: Union[str, None] = "0da41a57cfc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kernel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tool", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("output", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kernel")
    # ### end Alembic commands ###
