"""empty message

Revision ID: 9eb8e155fee8
Revises: 95e49e33bab7
Create Date: 2024-09-02 17:24:17.352478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9eb8e155fee8'
down_revision: Union[str, None] = '95e49e33bab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasource', schema=None) as batch_op:
        batch_op.drop_column('index_id')

    # ### end Alembic commands ###
