"""empty message

Revision ID: c98b9ff107ce
Revises: 93491b0e8563
Create Date: 2024-06-23 20:01:44.466220

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c98b9ff107ce"
down_revision: Union[str, None] = "93491b0e8563"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), nullable=False))
        batch_op.drop_column("title")

    # ### end Alembic commands ###
