"""empty message

Revision ID: cf364e7269d8
Revises: 3aa2694dff54
Create Date: 2024-08-04 13:36:17.890194

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf364e7269d8"
down_revision: Union[str, None] = "3aa2694dff54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sqlmodel.sql.sqltypes.AutoString(),
                server_default=sa.text("'builtin'"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
