"""empty message

Revision ID: e46bf1f7e482
Revises: e2bb4044bfe5
Create Date: 2024-07-24 14:31:19.901869

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e46bf1f7e482"
down_revision: Union[str, None] = "e2bb4044bfe5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasource", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("datasource", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.alter_column("connection_url", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("attributes", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("datasource_type")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasource", schema=None) as batch_op:
        batch_op.add_column(sa.Column("datasource_type", sa.VARCHAR(), nullable=False))
        batch_op.alter_column("attributes", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("connection_url", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("datasource")

    # ### end Alembic commands ###
