"""empty message

Revision ID: e68a643b4f42
Revises: 4d7ddfd4496c
Create Date: 2024-07-30 15:56:09.712726

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e68a643b4f42"
down_revision: Union[str, None] = "4d7ddfd4496c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vectorstore", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("offline_store", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.drop_column("offline_store_type")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vectorstore", schema=None) as batch_op:
        batch_op.add_column(sa.Column("offline_store_type", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("offline_store")

    # ### end Alembic commands ###
