name: Trigger auto deployment for aita-dataapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'dataapp/**'
    - '.github/workflows/aita-dataapp-AutoDeployTrigger-d01210a4-9fbb-4856-9829-90d40ded5b45.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/dataapp 
          registryUrl: aitaui.azurecr.io
          registryUsername: ${{ secrets.AITADATAAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AITADATAAPP_REGISTRY_PASSWORD }}
          containerAppName: aita-dataapp
          resourceGroup: aita
          imageToBuild: aitaui.azurecr.io/aita-dataapp:${{ github.sha }}
          dockerfilePath: Dockerfile

     

